// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "vue" {
  export interface GlobalComponents {
    CustomWindow: typeof import("./src/components/CustomWindow.vue")["default"];
    FeildSet: typeof import("./src/components/FeildSet.vue")["default"];
    FeildSetItem: typeof import("./src/components/FeildSetItem.vue")["default"];
    Footer: typeof import("./src/components/Footer.vue")["default"];
    LeftMenu: typeof import("./src/components/LeftMenu.vue")["default"];
    TopNav: typeof import("./src/components/TopNav.vue")["default"];
  }
}

export {};
