// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "vue" {
  export interface GlobalComponents {
    CarbonAddAlt: typeof import("~icons/carbon/add-alt")["default"];
    CarbonBasketball: typeof import("~icons/carbon/basketball")["default"];
    CarbonBat: typeof import("~icons/carbon/bat")["default"];
    CarbonBook: typeof import("~icons/carbon/book")["default"];
    CarbonUserAvatar: typeof import("~icons/carbon/user-avatar")["default"];
    CarbonUserAvatarFilled: typeof import("~icons/carbon/user-avatar-filled")["default"];
    FeildSet: typeof import("./components/FeildSet.vue")["default"];
    FeildSetItem: typeof import("./components/FeildSetItem.vue")["default"];
    LeftMenu: typeof import("./components/LeftMenu.vue")["default"];
    TopNav: typeof import("./components/TopNav.vue")["default"];
  }
}

export {};
